FROM liquibase/liquibase:4.33

WORKDIR /liquibase/changelog

COPY src/main/resources/db/changelog ./db/changelog
COPY src/main/resources/scripts/migrate.sh /usr/local/bin/migrate.sh

RUN chmod +x /usr/local/bin/migrate.sh && \
    sed -i 's/\r$//' /usr/local/bin/migrate.sh

ENTRYPOINT ["/usr/local/bin/migrate.sh"]