FROM liquibase/liquibase:4.33

WORKDIR /liquibase/changelog

COPY src/main/resources/db/changelog ./db/changelog
COPY --chmod=0755 src/main/resources/scripts/migrate.sh ./migrate.sh

ENTRYPOINT ["./migrate.sh"]