FROM liquibase/liquibase:4.33

WORKDIR /liquibase/changelog
COPY db/changelog ./db/changelog
COPY scripts/migrate.sh /usr/local/bin/migrate.sh
RUN chmod +x /usr/local/bin/migrate.sh

ENTRYPOINT ["/usr/local/bin/migrate.sh"]
