package com.example.reminderbot.model;

public enum SessionType {
    IMPORT_CATALOG_FILE,
    IMPORT_DB_FILE,
    NEW_TASK_TITLE,
    NEW_TASK_KIND,
    NEW_TASK_INTERVAL,
    NEW_TASK_NOTE,
    WAITING_WEBAPP_SUBSCRIPTION,
    CHANGE_TASK_SELECT,
    EDIT_TASK_SELECT,
    EDIT_TASK_PROPERTY,
    EDIT_TASK_VALUE
}
